#!/bin/bash

PINAME=9.20.202.130
#PINAME=192.168.1.133
#PINAME=9.20.202.187
#PINAME=192.168.1.90

scp -p mini-inst.sh pi@$PINAME:
scp -pr resources/ pi@$PINAME:
ssh pi@$PINAME ./mini-inst.sh
scp -p pi@$PINAME:node-red*.deb ./
ssh pi@$PINAME cat lint.log
