#!/bin/bash
echo -e '\033]2;'NODE-Red console'\007'
HOSTIP=`hostname -I | cut -d ' ' -f 1`
if [ "$HOSTIP" = "" ]; then
    HOSTIP="127.0.0.1"
fi
echo " "
echo "Once Node-RED has started, point a browser at http://$HOSTIP:1880"
echo " "
echo -e "Use   \033[0;36mnode-red-stop\033[0m                          to stop Node-RED"
echo -e "Use   \033[0;36mnode-red-start\033[0m                         to start Node-RED again"
echo -e "Use   \033[0;36msudo systemctl enable nodered.service\033[0m  to autostart Node-RED at every boot"
echo " "
echo "To find more nodes - go to http://flows.nodered.org"
echo "You may also need to install and upgrade npm"
echo -e "      \033[0;36msudo apt-get install npm\033[0m"
echo -e "      \033[0;36msudo npm i -g npm@2.x\033[0m"
echo " "
sudo service nodered start
sudo journalctl -f -u nodered -o cat
