#!/bin/bash
echo -e '\033]2;'NODE-Red console'\007'
echo " "
echo "Stop Node-RED"
echo " "
echo -e "Use   \033[0;36mnode-red-start\033[0m                         to start Node-RED again"
echo " "
sudo service nodered stop
echo " "
exit
