#!/bin/bash
echo -e '\033]2;'NODE-Red console'\007'
HOSTIP=`hostname -I | cut -d ' ' -f 1`
if [ "$HOSTIP" = "" ]; then
    HOSTIP="127.0.0.1"
fi
echo -e "\033[1mStart \033[38;5;88mNode-RED\033[0m"
echo " "
echo "Once Node-RED has started, point a browser at http://$HOSTIP:1880"
echo "On Pi Node-RED works better with the Iceweasel browser"
echo " "
echo -e "Use   \033[0;36mnode-red-stop\033[0m                          to stop Node-RED"
echo -e "Use   \033[0;36mnode-red-start\033[0m                         to start Node-RED again"
if [ -e "/bin/journalctl" ]; then
echo -e "Use   \033[0;36msudo systemctl enable nodered.service\033[0m  to autostart Node-RED at every boot"
else
echo -e "Use   \033[0;36msudo update-rc.d nodered defaults\033[0m      to autostart Node-RED at every boot"
fi
echo " "
echo "To find more nodes and example flows - go to http://flows.nodered.org"
sudo service nodered start
echo " "
if [ -e "/bin/journalctl" ]; then
    sudo journalctl -f -u nodered -o cat
else
    sudo tail -f /var/log/node-red.log
fi
